### ISSUE TITLE
Zygisk doesn't work on pixel 7a (zygote crashes too many times, rolling-back)

### ISSUE THREAD

**Issue by taylor00541** [pixincreate/Magisk#3]
Zygisk does not work. I can't attach logs but I assume this is a general issue, feel free to ask me questions. No modules are installed. 

Device: Pixel 7a (lynx)
Android version: 14
Magisk version name: 88d73b7b 27006 (built from soure)
Magisk version code: D

**Comment by pixincreate** [comment]
Operating System?

Without logs, I cannot help.
