### ISSUE TITLE
[Request] Guidance about rooting latest Graphene OS. 

### ISSUE THREAD

**Issue by DKMellow** [pixincreate/Magisk#4]
Hi, I am willing to ask if you could provide guidance in using this fork of Magisk to patch the latest versions of Graphene OS while maintaining Zygisk functionality since there doesn't seem to be any definitive guide to have Zygisk on Android 14 since all the changes. 

I would really appreciate it you could add this info to the README. md or under this Issue. 

Kind regards, Daniel.

**Comment by pixincreate** [comment]
Hi,
I'll surely update the README with regards to using my fork.
However, installation and usage process is same as official [Magisk](https://github.com/topjohnwu/Magisk). 

The difference is just that you'll be downloading and using root by trusting the keys that I use.

However, versions 27003+ have some serious regressions (you can check official [Magisk](https://github.com/topjohnwu/Magisk) issues).

In addition to that, modules like Shamiko will **not** work as the developers enforce signature verification.

**Comment by DKMellow** [comment]
Hi, 
As a update I wanted to say that I successfully rooted my new Pixel 9 Pro on Graphene OS and also having Zygisk.
Also successfully installing my baking apps. 

Thank you very much for you work! Truly a life saver for my use case.

![Screenshot_20241003-123244](https://github.com/user-attachments/assets/d6b6b74c-1004-4679-a1f9-3cd791bc4ea9)
