### ISSUE TITLE
Modules fail to install (GrapheneOS)

### ISSUE THREAD

**Issue by adcape** [pixincreate/Magisk#6]
GrapheneOS 2024112700 (Android 15), avbroot 3.9.0, ver 28001, Pixel 9

Modules fail to install, the app crashes. Tried playintegrityfix, playintegrityfork, jingmatrix/lsposed
Otherwise all looks normal, Zygisk - yes, Ramdisk - yes

**Comment by pixincreate** [comment]
Is it some how related to [this](
https://github.com/chenxiaolong/avbroot/issues/383)? and I believe it is **not**, but still, I have a hunch.

And yes, without logs, I cannot help.

**Comment by adcape** [comment]
> Is it some how related to [this](https://github.com/chenxiaolong/avbroot/issues/383)? and I believe it is **not**, but still, I have a hunch.
> 
> And yes, without logs, I cannot help.

The issue is not related to the mentioned discussion. All the rest runs perfectly fine.
Unfortunately logs contain no info about crashes when I attempts to install modules. If I manage to get more details, I'll re-open the issue.

In any case, thank you very much for the project and for the GrapheneOS support!

**Comment by pixincreate** [comment]
You can check official Magisk documentation that can help catch the logs.

**Comment by adcape** [comment]
Just for the info: with version 28002 everything works as expected. A great tool!

**Comment by pixincreate** [comment]
glad to know that it works!
